spring.config.activate.on-profile=dev

logging.level.org.springframework.security=DEBUG

server.port=8081

spring.application.name=edu-manager

spring.web.locale=es_CL

spring.datasource.url=jdbc:mysql://localhost:3307/edu
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

spring.jpa.properties.hibernate.default_schema=edu
spring.jpa.properties.hibernate.hbm2ddl.auto=none
  
# jwt.expired=3600000
# jwt.secret=secret
# jwt.roles.full=dev_admin,admin
# jwt.roles.onlyRead=grocer
# jwt.roles.onlyInsert=grocer
# jwt.roles.onlyUpdate=grocer
# jwt.roles.readInsert=secretary,grocer
# jwt.roles.readUpdate=grocer
# jwt.roles.insertUpdate=grocer